# render.yaml

services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: "apt-get update && apt-get install -y libzbar0 && pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host=0.0.0.0 --port=10000"
    plan: free
    envVars:
      - key: PORT
        value: 10000
